export  const irregularVerbsData = [
  { infinitive: 'begin', pastSimple: 'began', pastParticiple: 'begun' },
  { infinitive: 'break', pastSimple: 'broke', pastParticiple: 'broken' },
  { infinitive: 'choose', pastSimple: 'chose', pastParticiple: 'chosen' },
  { infinitive: 'come', pastSimple: 'came', pastParticiple: 'come' },
  { infinitive: 'do', pastSimple: 'did', pastParticiple: 'done' },
  { infinitive: 'drink', pastSimple: 'drank', pastParticiple: 'drunk' },
  { infinitive: 'eat', pastSimple: 'ate', pastParticiple: 'eaten' },
  { infinitive: 'find', pastSimple: 'found', pastParticiple: 'found' },
  { infinitive: 'go', pastSimple: 'went', pastParticiple: 'gone' },
  { infinitive: 'have', pastSimple: 'had', pastParticiple: 'had' },
  { infinitive: 'know', pastSimple: 'knew', pastParticiple: 'known' },
  { infinitive: 'run', pastSimple: 'ran', pastParticiple: 'run' },
  { infinitive: 'see', pastSimple: 'saw', pastParticiple: 'seen' },
  { infinitive: 'speak', pastSimple: 'spoke', pastParticiple: 'spoken' },
  { infinitive: 'take', pastSimple: 'took', pastParticiple: 'taken' },
  { infinitive: 'write', pastSimple: 'wrote', pastParticiple: 'written' },
];
